### ISSUE TITLE
FsXaml 2.0 Beta

### ISSUE THREAD

**Issue by ReedCopsey** [fsprojects/FsXaml#33]
Please consider testing out the new prerelease of FsXaml 2.0, and leaving comments and ideas below.

NuGet package published at https://www.nuget.org/packages/FsXaml.Wpf/2.0.0-beta1

This release includes significant improvements to the generated code related to all XAML types.  The containers and factories no longer exist - loading XAML files into a generated type is much more aligned with the results from C# code generation (with some differences, described below).

### Major Changes

- `UserControl` types no longer are wrapped within a `ContentControl` when loaded from XAML. The "root" of the visual tree is the control itself, which means better efficiency, but also eliminates some of the bugs present in the previous version of FsXaml.
- `Application` and `ResourceDictionary` no longer use factories. The `XAML<>` provider creates the Application or Resource Dictionary subclass directly.  This is a breaking change from previous version - for example, instead of `App().Root.Run()` you just do `App().Run()`.
- The `IViewController` and specific view controller classes have been removed. The `ViewController` types in previous versions were intended as a way to duplicate "code behind" style functionality. Since we now create types directly, and have flagged them as inheritable, you can write code behind directly in a subclass. Detailed examples exists in the demos.  For an example, see: https://github.com/fsprojects/FsXaml/blob/master/demos/WpfSimpleMvvmApplication/MainView.xaml.fs#L5-L18
- `FrameworkElement` types automatically load all named elements.  The 2nd static parameter to the type provider has been removed, and is automatically treated as if it were `true`. Types without named elements do not create the accessors or incur extra overhead, as the type provider handles the checking internally.
- `ResourceDictionary` types (and `Application`) no longer create elements for items by `x:Key`. You can create a resource dictionary, but need to access it as a dictionary (which is more aligned with C#).
- Added `Wpf` module with utilites which allow for installation of synchronization context prior to creating the application. This is required if doing asynchronous work within types that are generated directly from the main windows

### Breaking Changes

- The factory type removal means removing the extra `.Root` from application and resource dictionaries.  
- ViewControllers no longer exist. Convert to using code behind directly.

### Known Issues

- Use of code behind from within the main, startup window does not work. The easy workaround is to create the main window in code, such as in this demo: https://github.com/fsprojects/FsXaml/blob/master/demos/WpfMvvmAgent/App.fs#L9-L10
- Visual F# Power Tools will report erroneous errors when subclassing generated types from a type provider. Every use of code behind causes 3 errors to show up if Power Tools is enabled. (The compiler handles it fine, and doesn't report errors, but if power tools is enabled, you get 3 that show up after compile, and red squigglies in the editor.)

### Tasks prior to 2.0 RTM

- [x] Report issue with Visual F# Power Tools and inherting from generated types
- [x] See what can be done about #24 
- [x] Handle issue #34 
- [x] ~~Migrate supplied behaviors to attached properties~~ Moved to future in #35
- [x] Remove dependency of Expression.Blend.Sdk
- [x] Optional: Ship behaviors as separate NuGet/Project? (Please comment on whether Blend support is important to you - or this may be dropped)

Please try the new package, and let me know of any issues, ideas, or improvements that need to happen prior to 2.0.

Thank you!
Reed

**Comment by brianberns** [comment]
Could you please comment on the proliferation of temporary files that I reported (#24)? This is my #1 issue with FsXaml, but you haven't addressed it yet. Thanks.

**Comment by ReedCopsey** [comment]
Reported issue with type provider to FS Power Tools: https://github.com/fsprojects/VisualFSharpPowerTools/issues/1388

**Comment by brianberns** [comment]
Never mind. I see now that you’ve marked it as a bug and are fixing it. Thanks.

 

-- Brian

**Comment by ReedCopsey** [comment]
I suspect the issue related to Visual F# Power Tools may be due to it using the old version internally - I'll do a PR there once 2.0 is final. See https://github.com/fsprojects/VisualFSharpPowerTools/issues/1388#issuecomment-218607203

**Comment by fralken** [comment]
Now I cannot figure out how to access the main window from code.

Before, I had [this code in MainWindow.xaml.fs](https://github.com/fralken/MyKinectF/blob/master/MyKinectF/MainWindow.xaml.fs#L8-L18) so that I could access the window (to move it on a secondary monitor, btw).

Now I'm trying something like

```
/// Top-level container for all XAML elements.
type MainWindowBase = XAML<"MainWindow.xaml">

type MainWindow() as self = 
    inherit MainWindowBase()

    do
        let window = self
        ...
```
but it doesn't work.

Also, the window opens with a menu below the top border (in the middle) that looks like a Designer tool, with 3 buttons ("Go to live visual tree", "Enable selection", "Display layout adorners").
In MainWindow.xaml I removed the reference to the ViewController

**Comment by ReedCopsey** [comment]
@fralken You should be able to do something like:

```fsharp
/// Top-level container for all XAML elements.
type MainWindowBase = XAML<"MainWindow.xaml">

type MainWindow() as self =     
    inherit MainWindowBase ()

    do
        self.Loaded.Add(fun _ ->
            let window = self
            try
                let secondaryScreen = Forms.Screen.AllScreens |> Array.find (fun (s: Forms.Screen) -> not s.Primary)                
                let workingArea = secondaryScreen.WorkingArea
                let w = Point(float workingArea.Left, float workingArea.Top)
                let t = PresentationSource.FromVisual(window).CompositionTarget.TransformFromDevice
                let p = t.Transform(w)
                window.Left <- p.X
                window.Top <- p.Y
            with
                | _ -> ignore
            window.WindowState <- WindowState.Maximized)
```

The window should always be Loaded in the Loaded event, so the IsLoaded checks shouldn't be necessary (which should have been true before, too).

Note that, if you're specifying the window as the StartupUri in App.xaml, you may also need to undo that and do this to load the application: https://github.com/fsprojects/FsXaml/blob/master/demos/WpfMvvmAgent/App.fs#L9-L10

**Comment by ReedCopsey** [comment]
@fralken Also, the designer issue sounds like you have this turned on: https://msdn.microsoft.com/en-us/library/mt270227.aspx

**Comment by fralken** [comment]
Thank you! It works. (btw, I agree that the IsLoaded check was redundant and useless)

This new FsXaml gives more control on the window (like in C#). This is very helpful.

As for the designer issue, again you were right. It was not related to FsXaml (obviously), but rather that I just updated to VS 2015 update 2, and probably it activated the feature.
Thank you again for pointing me in the right direction.

**Comment by M0ns1gn0r** [comment]
> `ResourceDictionary` types (and Application) no longer create elements for items by x:Key. You can create a resource dictionary, but need to access it as a dictionary (which is more aligned with C#).

This could be more aligned with C#, but the FsXaml library is created for F#, and the main purpose of F#'s `TypeProvider`s (at least in my opinion) is to provide faster feedback by replacing run-time checks (which you get with indexers ["key"]) with compile-time ones.

**Comment by Evangelink** [comment]
When you talk about Blend support do you mean only behaviors or are you suggesting that you have a way to load your f# project in Blend? Because I still use a C# project for my views just to be able to use Blend for some styling and stuff.

**Comment by ReedCopsey** [comment]
@Evangelink Unfortunately, Blend support at that level isn't really something possible for the community to enable.  Microsoft would have to add that.

I was more talking about blend support for the behaviors (ie: drag and drop behaviors for EventToCommand/EventToMailbox/etc).

On a side note - you can workaround lack of F# support in Blend by having a "fake" csproj, and just adding the xaml files in.  You don't need the code behind files for Blend to work, so a project just containing your xaml will allow you to edit the xaml in blend, and still use F# for all of the actual compiled results.

**Comment by ReedCopsey** [comment]
@M0ns1gn0r Yes, agreed, somewhat.  The main purpose of the type provider, in my mind, is to allow WPF/XAML to actually function from F#... Without real types, you can't embed views, etc.  The access to named elements, and especially the code behind features of 2.0, are an attempt to bring it closer to C# tooling standards.

The problem with resources from the type provider standpoint is that the built-in xaml parsing libraries do not actually support resource types - we had to add in our own "dictionary" of translators for types, and it was always very, very buggy.  Also, resource access from code is something that's not really used very often, since they're typically for other xaml files.

I am hoping to create some tooling to help with that scenario, as well as with binding support to help support not using "magic strings" as much here soon.  That may be an easier, viable long term solution for this.

**Comment by ReedCopsey** [comment]
All tasks are now done in final NuGet Packages.

https://www.nuget.org/packages/FsXaml.Wpf/2.0.0-beta4 and https://www.nuget.org/packages/FsXaml.Wpf.Blend/

Contain the "RC" versions of FsXaml 2.0.  Please test and give feedback.

If I don't hear of any problems, I plan to release early next week.

**Comment by ReedCopsey** [comment]
Just released 2.0 final: https://www.nuget.org/packages/FsXaml.Wpf and https://www.nuget.org/packages/FsXaml.Wpf.Blend/2.0.0

**Comment by brianberns** [comment]
After upgrading to 2.0.0, I have some sort of lingering reference to 0.9.9 that I cannot get rid of. My app compiles and runs fine with 2.0.0, but Intellisense shows this error:

_The type provider 'FsXaml.XamlTypeProvider' reported an error: Could not load type 'FsXaml.NamedNodeAccessor' from assembly 'FsXaml.Wpf, Versionn=0.9.9.0, ..."_

I've done everything I can think of to clear any cached versions of 0.9.9 from my machine, but the problem reappears as soon as I open my .fs file in Visual Studio. Any ideas what's going on?

![untitled](https://cloud.githubusercontent.com/assets/11883138/15309505/7d18794c-1bb5-11e6-9c86-b5ea7fbd7995.png)

**Comment by ReedCopsey** [comment]
@brianberns It's probably Visual F# Power Tools. See https://github.com/fsprojects/VisualFSharpPowerTools/issues/1388

I've already filed a PR to fix it: https://github.com/fsprojects/VisualFSharpPowerTools/pull/1392

If you can, try disabling power tools, and see if it goes away.  If so, that PR should fix it once it's applied (you should be able to download a daily once they accept it).  The issue is the power tools uses the old version, which generates types differently, and it confuses Visual Studio.

**Comment by brianberns** [comment]
Yep, that’s exactly what I’m seeing. Thank you.

**Comment by ReedCopsey** [comment]
@brianberns Just realized - you can actually fix it _now_ if you want.  The pull request generates a new vsix. If you want to fix it immediately, you can install the vsix from VFPT at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.0-a1605170311/artifacts
